# Thư viện và xử lí data

In [27]:
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
import json
from sklearn.preprocessing import LabelEncoder

In [28]:
data_raw = "./file_csv/train_PTIT.csv"
df = pd.read_csv(data_raw)

In [29]:
df["subject"].unique()

array(['Probabilistic_Methods', 'Neural_Networks', 'Genetic_Algorithms',
       'Rule_Learning', 'Reinforcement_Learning', 'Case_Based', 'Theory'],
      dtype=object)

In [30]:
name_2_Id = {
    "Probabilistic_Methods": 0,
    "Neural_Networks": 1,
    "Genetic_Algorithms": 2,
    "Rule_Learning": 3,
    "Reinforcement_Learning": 4,
    "Case_Based": 5,
    "Theory": 6,
}   
# create dict to repplace
id_2_Name = {
    "0": "Probabilistic_Methods",
    "1": "Neural_Networks",
    "2": "Genetic_Algorithms",
    "3": "Rule_Learning",
    "4": "Reinforcement_Learning",
    "5": "Case_Based",
    "6": "Theory",
}

In [31]:
# preprocessing subject
df["subject"] = df["subject"].map(name_2_Id)
df

w_0  w_1  w_2  w_3  w_4  w_5  w_6  w_7  w_8  w_9  ...  w_1424  w_1425  \
0       0    0    0    0    0    0    0    0    0    0  ...       0       0   
1       0    0    0    0    0    0    0    0    0    0  ...       0       0   
2       0    0    0    0    0    0    0    0    0    0  ...       0       1   
3       0    0    0    0    0    0    0    0    0    0  ...       0       0   
4       0    0    0    0    0    0    0    0    0    0  ...       0       0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...     ...     ...   
2432    0    0    0    0    0    0    0    0    0    0  ...       0       0   
2433    0    0    0    0    0    0    0    0    0    0  ...       0       0   
2434    0    0    0    0    0    0    0    0    0    0  ...       0       0   
2435    0    0    0    1    0    0    0    0    0    0  ...       0       0   
2436    0    0    0    0    0    0    0    0    0    0  ...       0       0   

      w_1426  w_1427  w_1428  w_1429  w_1430  w_1431  w_1432  subject  
0          0       0       0       0       0       0       0        0  
1          0       0       0       0       0       0       0        1  
2          0       0       0       0       0       0       0        2  
3          0       0       0       0       0       0       0        3  
4          0       0       0       0       0       0       0        2  
...      ...     ...     ...     ...     ...     ...     ...      ...  
2432       0       0       0       0       0       0       0        2  
2433       0       0       0       0       0       0       0        6  
2434       0       0       0       0       0       0       0        0  
2435       0       0       0       0       0       0       0        1  
2436       0       0       0       0       0       0       0        4  

[2437 rows x 1434 columns]

In [32]:
# train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.iloc[:, :-1], df.iloc[:, -1], test_size=0.2, random_state=42
)

In [33]:
# thư viện tính toán % predict
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

# KNN

In [34]:
from sklearn import neighbors

In [35]:
clf = neighbors.KNeighborsClassifier(n_neighbors = 5, weights = 'distance', metric='cosine')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print("KNN accuracy: ", accuracy_score(y_test, y_pred))
print("KNN f1 score: ", f1_score(y_test, y_pred, average='weighted'))
print("KNN confusion matrix: ")
print(confusion_matrix(y_test, y_pred))

KNN accuracy:  0.7622950819672131
KNN f1 score:  0.7609161666582465
KNN confusion matrix: 
[[ 53   5   2   2   2   1   2]
 [ 12 130   3   1   1   3   8]
 [  2   2  68   0   2   0   3]
 [  1   4   1  20   0   2   6]
 [  1   4   2   2  20   3   1]
 [  3   4   2   5   0  43   0]
 [  3   9   3   4   2   3  38]]


# Logistic Regression

In [36]:
from sklearn.linear_model import LogisticRegression
# https://www.miai.vn/2020/06/16/oanh-gia-model-ai-theo-cach-mi-an-lien-chuong-2-precision-recall-va-f-score/

In [37]:
regressor = LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=643, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
regressor.fit(X_train, y_train)

# predict
predictions = regressor.predict(X_test)
# evaluate
print("LR classification accuracy", accuracy_score(y_test, predictions))

# matrix confusion
cm = confusion_matrix(y_test, predictions)
print(cm)

# f1 score
print("LR f1 score", f1_score(y_test, predictions, average="macro"))

LR classification accuracy 0.7930327868852459
[[ 55   6   1   2   1   2   0]
 [ 13 136   1   0   1   2   5]
 [  1   7  65   1   1   1   1]
 [  2   2   2  18   0   2   8]
 [  2   5   2   0  21   1   2]
 [  2   1   2   3   2  45   2]
 [  1   5   2   4   0   3  47]]
LR f1 score 0.7576601646430857


# SVM

In [39]:
# svm to classify
from sklearn.svm import SVC

clf = SVC(kernel='linear', probability=True)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print("SVM accuracy: ", accuracy_score(y_test, y_pred))
print("SVM f1 score: ", f1_score(y_test, y_pred, average='weighted'))
print("SVM confusion matrix: ")
print(confusion_matrix(y_test, y_pred))

SVM accuracy:  0.7663934426229508
SVM f1 score:  0.7653468326532188
SVM confusion matrix: 
[[ 55   5   1   2   1   2   1]
 [ 16 131   1   2   2   2   4]
 [  2  11  60   1   1   1   1]
 [  2   1   0  21   0   4   6]
 [  2   5   4   0  19   1   2]
 [  2   4   3   2   1  42   3]
 [  0   7   2   4   0   3  46]]
