# Library

In [92]:
import gym
import numpy as np
import random

# Funtion strategy

In [93]:
env = gym.make("Taxi-v3", render_mode="ansi")
env.reset()


(323, {'prob': 1.0, 'action_mask': array([1, 1, 1, 0, 0, 0], dtype=int8)})

In [94]:
print(env.reset())
print(env.render())

(151, {'prob': 1.0, 'action_mask': array([1, 1, 1, 0, 0, 0], dtype=int8)})
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+




In [95]:
state = env.encode(3, 1,0, 2)
print("state: ", state)
env.re
env.s = state
print(env.render())

state:  322
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+




In [96]:
print(list(env.decode(208)))

[2, 0, 2, 0]


In [97]:
display(env.P[322])

{0: [(1.0, 422, -1, False)],
 1: [(1.0, 222, -1, False)],
 2: [(1.0, 342, -1, False)],
 3: [(1.0, 322, -1, False)],
 4: [(1.0, 322, -10, False)],
 5: [(1.0, 322, -10, False)]}

In [98]:
q_table = np.zeros((env.observation_space.n, env.action_space.n))
print(q_table)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [99]:
total_episodes = 50000        # Total episodes
total_test_episodes = 100     # Total test episodes
max_steps = 99                # Max steps per episode

learning_rate = 0.7           # Learning rate
gamma = 0.618                 # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability
decay_rate = 0.01             # Exponential decay rate for exploration prob

In [100]:
def Strategy(x, y, pickup, dropout):


    pass


In [101]:
# Strategy()
env.close()